= {lab_name}
:toc:
:toc-placement: preamble
:sectnums:
:icons: font

== Workshop Instuctions ==

=== Build insecure image ===
. Login to RHDH on the development machine with user1 and password
. Go the *Create* and select the insecure GPT and use default values and click Create
. Click on the devspaces link on the software component and trigger a source code change
. Wait for the pipeline to complete.  Take note of the image url and tag being generated.

=== Deploy insecure image to QA ==
. SSH into the qa bastion
. Run these commands
. sh deploy-insecured.sh

=== Enable Tekton Chains Image Signing ===
. SSH into the development server
. Create cosign signing secret.  This will be used by Tekton Chains to sign your container images using the password and private key embedded in the secret.
+
[source, role="execute"]
----
COSIGN_PASSWORD=openshift cosign generate-key-pair k8s://openshift-pipelines/signing-secrets
----
. A *cosign.pub* file will be created in the current directory.  This will be used later for image signature verification.
. Enable Image Signing
+
[source, role="execute"]
----
cd
cat <<EOF >> tekton-config.yaml
apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  addon: {}
  chain:
    artifacts.oci.storage: oci
    artifacts.taskrun.format: in-toto
    artifacts.taskrun.storage: oci
    artifacts.pipelinerun.format: in-toto
    artifacts.pipelinerun.storage: oci
    transparency.enabled: true
    transparency.url: http://rekor-server.rekor-system.svc
  config: {}
EOF
oc patch TektonConfig config --type='merge' --patch "$(cat tekton-config.yaml)"
----
. cat cosign.pub --> Remember to switch back to this output to grab the contents

=== Build secure image ==
. Switch back to RHDH in the development machine
. Go the *Create* and select the secure GPT and use default values and click Create (notice that the verify commits option is enabled)
. Open the VNC server with password {common_password}
. Click on *Activities* and look for *VS Code*
. In *VS Code* click on the *Source Code* icon on the left menu
. Click on *Clone Repository*
. Paste in this url https://user1:{common_password}@gitlab-gitlab.apps.cluster-.....opentlc.com/development/secured-app.git, click *Select as Repository Location* and then click *Open*
. Make a change to the source code e.g. README.md
. Click on *Source Code* on the left menu, click on stage all changes (+ sign next to `Changes`) and then type a commit message and click *Commit*
. A browser will open requesting credentials. This is the TAS (Trusted Artifact Signer) requiring credentials to sign you git commit.  Enter user1:{common_password} and *Sign In*
. Close the browser and switch back to *VS Code*
. Click *Sync Changes*
. Switch back to RHDH and click on *Catalog* on the left menu and then locate the *secured-app* component.
. Select the *CI* tab
. Wait for the pipeline to complete.  Take note of the image url and tag being generated.
. Explain the different steps in the pipeline and views shown (ACS and SBOM)
. Login to quay and show the cosign tick on the *latest* tag

=== Enable Enterprise Contract Validation ===
. Run the following commands
. vi cosign.pub --> Paste the contents from the ssh session in the development server
. cosign initialize --mirror={tuf_mirror} --root={tuf_mirror}/root.json
. sh validate-insecured.sh
. success will be false
. sh validate-secured.sh
. success will be true

=== Enable ACS Signature Verification ===
 Go to the {acs_route}[RHACS Console,window=_blank] and log in with your credentials username: *{acs_portal_username}* and password: *{acs_portal_password}*.
. On the left menu, select *Platform Configuration > Integrations*
. On the *Integrations* screen, select *Signature Integrations*
. On the *Signature Integrations*, click the button *New integration*
.. For *Integration name* enter *cosign*
.. Expand the *Cosign* field and select *Add new public key*
.. For *Public key name* enter *cosign.pub*
.. For *Public key value* copy the public key from the *development* terminal and paste it in this field.  This is used by RHACS to verify your image signatures.  Ensure you copy the entire contents of the file i.e.
+
[source,textinfo]
----
-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----
----
. Click save
. For convenience, we have already set up a policy in ACS called *0-Trusted Signature Policy* that checks an image for a valid signature.  This policy is enforced during the below lifecycle stages:
.. Build  - Runs when doing a roxctl image check on an image.  This will trigger a violation if the image passed to the command is not signed with our signature.
+
This policy is currently disabled.
+
. On the left menu, select *Platform Configuration > Policy Management*
. The policy you are looking for is called *0-Trusted Signature Policy*.  It should be at the top of the list.
. Click the ellipse at the end and select *Edit policy*.
. Select *Policy criteria* and then click the *Select* button.
. Select the cosign signature integration and click save.
. Click *Next* to get to the *Policy Scope* screen and click on *Add inclusion scope*
. Select *production* as the cluster and *qa* as the namespace.
. Continue clicking next at the bottom until you finally save the policy.
. Now that the policy is updated, we want to enable it.  Click the ellipse again for the same policy and select *Enable policy*

=== Deploy both images ===
. We are now going to test the ACS policy against our insecure-app image.
. Swith back to the qa bastion
. Run these commands
.. sh deploy-insecured.sh
.. Policy failure
.. sh deploy-secured.sh
.. Deployment successful
.. navigate to https://secure-qa.apps.cluster.....opentlc.com to show app running
